name: Build and upload artifact
on:
  release:
    types: [created]

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build artifact
        working-directory: ./dist
        run: tar -czvf dist.tar.gz index.js

      - name: upload artifact
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "dist/dist.tar.gz"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.event.release.tag_name }}
